name: speedrun

services:
  postgres:
    build: 
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_DB=speedrun
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres
    ports:
      - "5432"
    volumes:
      - data_sql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - uploads:/speedrun/uploads
    environment:
      - POSTGRES_DB=speedrun
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - ORIGIN=http://localhost:3000

volumes:
  data_sql:
  uploads: